// Provides video mode definitions, VRAM access, palette memory,
// and display control functions such as SetMode().
#include <gba_video.h>

// Provides GBA BIOS/system calls such as VBlankIntrWait().
#include <gba_systemcalls.h>

// Provides interrupt functions such as irqInit() and irqEnable().
#include <gba_interrupt.h>

// Provides DMA copy functions.
// DMA is used to copy data quickly to VRAM or palette memory.
#include <gba_dma.h>

// Provides common GBA types such as u16, u32, etc.
#include <gba_types.h>

// Header generated by grit.
// It contains the converted image bitmap and palette data.
//
// For MODE_4, grit should generate something like:
// imageBitmap -> 8 bpp image data
// imagePal    -> 256-color palette
#include "image.h"

// MODE_4 uses a 256-color palette.
// Each palette entry is a 16-bit GBA color.
#define PALETTE_COLORS 256

// Number of frames used for the fade-in effect.
//
// The GBA runs at around 60 frames per second.
// 15 frames is roughly 0.25 seconds.
// 30 frames is roughly 0.5 seconds.
// 60 frames is roughly 1 second.
#define FPS_FADE_IN 15

// Temporary palette used during the fade-in.
// Instead of modifying the original imagePal directly,
// we create a faded version here and copy it to BG_PALETTE.
u16 fadePalette[PALETTE_COLORS];

// Sets the background palette to black.
//
// This makes the image start invisible, because the bitmap is already
// in VRAM but all palette colors are black.
void setBlackPalette(void) {

    // Fill the temporary palette with black.
    //
    // In GBA 15-bit color:
    // 0 means black.
    for (int i = 0; i < PALETTE_COLORS; i++) {
        fadePalette[i] = 0;
    }

    // Copy the black palette to the GBA background palette memory.
    //
    // BG_PALETTE is where background palettes are stored.
    // Each color is u16, so 256 colors = 256 * sizeof(u16) bytes.
    dmaCopy(fadePalette, BG_PALETTE, PALETTE_COLORS * sizeof(u16));
}

// Performs a fade-in by gradually restoring the original image palette.
//
// This is efficient because MODE_4 uses a palette.
// Instead of changing every pixel, we only change the 256 palette colors.
void fadeInPalette(int frames) {

    // step goes from 0 to frames.
    //
    // step = 0      -> completely black
    // step = frames -> original palette
    for (int step = 0; step <= frames; step++) {

        // Process every color in the palette.
        for (int i = 0; i < PALETTE_COLORS; i++) {

            // Read the original color generated by grit.
            //
            // GBA colors are stored as 15-bit BGR:
            // bits 0-4   = red
            // bits 5-9   = green
            // bits 10-14 = blue
            u16 color = imagePal[i];

            // Extract the red component.
            int red = color & 0x1F;

            // Extract the green component.
            int green = (color >> 5) & 0x1F;

            // Extract the blue component.
            int blue = (color >> 10) & 0x1F;

            // Scale each color component depending on the current fade step.
            //
            // At the beginning:
            // step is 0, so every color becomes 0.
            //
            // At the end:
            // step equals frames, so the original color is fully restored.
            red = (red * step) / frames;
            green = (green * step) / frames;
            blue = (blue * step) / frames;

            // Rebuild the GBA 15-bit color from red, green, and blue.
            fadePalette[i] = red | (green << 5) | (blue << 10);
        }

        // Wait until the next VBlank before changing the palette.
        //
        // This avoids updating graphics memory while the screen is drawing.
        VBlankIntrWait();

        // Copy the faded palette to the real GBA background palette memory.
        dmaCopy(fadePalette, BG_PALETTE, PALETTE_COLORS * sizeof(u16));
    }
}

// Program entry point.
int main(void) {

    // Initialize the interrupt system.
    irqInit();

    // Enable the VBlank interrupt.
    //
    // VBlankIntrWait() needs this to work correctly.
    irqEnable(IRQ_VBLANK);

    // Enable interrupts globally.
    //
    // Without this, VBlankIntrWait() may never continue.
    REG_IME = 1;

    // Set the GBA to MODE_4.
    //
    // MODE_4 is a 240x160 bitmap mode using 8 bits per pixel.
    // Each pixel is an index into a 256-color palette.
    //
    // BG2_ON enables background 2, which is used by bitmap modes.
    SetMode(MODE_4 | BG2_ON);

    // Start with a completely black palette.
    //
    // The image data can already be copied to VRAM, but it will not be
    // visible yet because all palette colors are black.
    setBlackPalette();

    // Copy the image bitmap generated by grit into VRAM.
    //
    // imageBitmap contains the 8 bpp image data.
    // imageBitmapLen is the size in bytes.
    //
    // VRAM is defined as a numeric address, so it is cast to void*
    // because dmaCopy() expects a pointer destination.
    dmaCopy(imageBitmap, (void*)VRAM, imageBitmapLen);

    // Fade from the black palette to the real image palette.
    fadeInPalette(FPS_FADE_IN);

    // Main loop.
    // GBA programs usually keep running forever.
    while (1) {

        // Wait for the next frame.
        VBlankIntrWait();
    }
}
