// Provides video mode definitions, VRAM access, and display control functions.
#include <gba_video.h>

// Provides GBA BIOS/system calls such as VBlankIntrWait().
#include <gba_systemcalls.h>

// Provides interrupt functions such as irqInit() and irqEnable().
#include <gba_interrupt.h>

// Provides DMA copy functions used to quickly copy data into video memory.
#include <gba_dma.h>

// Header generated by grit.
// It contains the converted image data and its size.
#include "image.h"

// Program entry point.
int main(void) {

    // Initialize the interrupt system.
    // This must be done before enabling interrupts.
    irqInit();

    // Enable the VBlank interrupt.
    // VBlankIntrWait() needs this interrupt to work correctly.
    irqEnable(IRQ_VBLANK);

    // Set the GBA video mode.
    //
    // MODE_3 is a 240x160 bitmap mode using 16 bits per pixel.
    // BG2_ON enables background 2, which is used by bitmap modes.
    SetMode(MODE_3 | BG2_ON);

    // Copy the image data generated by grit into VRAM.
    //
    // imageBitmap is the converted 16 bpp bitmap data.
    // VRAM is the video memory address.
    // imageBitmapLen is the total size of the image data in bytes.
    //
    // VRAM is defined as a numeric address, so it is cast to void*
    // because dmaCopy() expects a pointer destination.
    dmaCopy(imageBitmap, (void*)VRAM, imageBitmapLen);

    // Main loop.
    // GBA programs usually keep running forever.
    while (1) {

        // Wait for the next vertical blank period.
        // This keeps the program synchronized with the screen refresh.
        VBlankIntrWait();
    }
}
